### ISSUE TITLE
dnacenter_sda_virtual_network_v2 fails on state refresh

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#108]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
When doing state refresh(terraform plan) for dnacenter_sda_virtual_network_v2 dnac provider might sometimes fail. If I interpret logs correctly, the provider hits API rate limit a couple times and gives up instead of continuing to retry. 
Relevant terraform output:
```
dnacenter_sda_virtual_network_v2.vn["INFRA_VN"]: Refreshing state... [id=virtual_network_name:=INFRA_VN]
dnacenter_sda_virtual_network_v2.vn["CORP_VN"]: Refreshing state... [id=virtual_network_name:=CORP_VN]
dnacenter_sda_virtual_network_v2.vn["CORP_VN3"]: Refreshing state... [id=virtual_network_name:=CORP_VN3]
dnacenter_sda_virtual_network_v2.vn["CORP_VN2"]: Refreshing state... [id=virtual_network_name:=CORP_VN2]
╷
│ Error: Failure when executing GetVirtualNetworkWithScalableGroups
│
│   with dnacenter_sda_virtual_network_v2.vn["CORP_VN"],
│   on sda_vn.tf line 2, in resource "dnacenter_sda_virtual_network_v2" "vn":
│    2: resource "dnacenter_sda_virtual_network_v2" "vn" {
│
│ error with operation GetVirtualNetworkWithScalableGroups
╵
╷
│ Error: Failure when executing GetVirtualNetworkWithScalableGroups
│
│   with dnacenter_sda_virtual_network_v2.vn["CORP_VN3"],
│   on sda_vn.tf line 2, in resource "dnacenter_sda_virtual_network_v2" "vn":
│    2: resource "dnacenter_sda_virtual_network_v2" "vn" {
│
│ error with operation GetVirtualNetworkWithScalableGroups
╵
```
TF log: [tf.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10069780/tf.log)

**Expected behavior**
If my speculation about API rate limit is correct the provider is supposed to keep retrying. Ideally amount attempts, timeout and back-off strategy should be configurable in the provider. More info on api retry back-off strategy here: [https://medium.com/capital-one-tech/3-best-practices-for-api-clients-feef9ec97f1a](url)

**Screenshots**
<img width="739" alt="image" src="https://user-images.githubusercontent.com/9823462/203385750-09fda6d1-e892-45e0-986d-d56b14059e76.png">

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.4-72142
* Terraform version: 1.3.4
* Cisco DNA Center provider version: 1.0.13-beta
* OS Version: macOS 12.6.1

**Comment by fmunozmiranda** [comment]
Hey @mschedrin error I can see is next one:
```json
{
   "error": "Rate Limit exceeded; BapiName: Get default authentication profile from SDA Fabric, RateLimit config details: RateLimitContext{rate=100, windowUnit='minute', windowDuration=1, maxConcurrentExecutionsPermitted=1}",
   "bapiExtendedStatusCode": "REJECTED_ABOVE_MAX_CONCURRENCY_LIMIT",
   "bapiExtendedStatusDescription": "For BAPI: Get default authentication profile from SDA Fabric, DNACP Runtime is at maximum allowed concurrent BAPI executions: 1"
}
```
I think if you use `depends_on` for each `sda_resource` problem should be solved, because API says it's not possible to execute more than 1 concurrent operation.
Could you try it and let us know how does it go.

**Comment by mschedrin** [comment]
Yes, that might solve this exact issue, but I've seen BAPI limit stopping terraform plan/apply/destroy many times. Do you handle those rate limits in the provider? It's worth doing and it will remediate many issues with usage of provider. 
I can imagine following workflow: 
If error 429(too many requests) is returned from DNAC, you introduce delayed retry with back-off timer. This means that you wait for, let's say 5 seconds and retry, if it still fails you wait twice as long - 10 seconds and retry again, further keep retrying until max attempts has reached. It would be also nice to have it configurable in provider settings.

**Comment by wastorga** [comment]
Hi, @mschedrin.

I think that you were able to do this using the resource: dnacenter_sda_virtual_network (#107)

Can you confirm that the fix provided there helped you with this one?
