### ISSUE TITLE
Provider crash on dnacenter_reserve_ip_subpool

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#110]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
Yes, see debug log attached in additional context section.
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
Provider crashes when running terraform apply:
```
dnacenter_reserve_ip_subpool.this["NW02_CORP_VN"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to dnacenter_reserve_ip_subpool.this["NW02_CORP_VN"], provider "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]" produced an unexpected new
│ value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Expected behavior**
Provider is not supposed to crash.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.4-72142
* Terraform version: 1.3.4
* Cisco DNA Center provider version: 1.0.13-beta
* OS Version: macOS 12.6.1

**Additional context**
TF debug log: [tf.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10077343/tf.log)

**Comment by fmunozmiranda** [comment]
@zapodeanu This is the problem that I had mentioned before, of the status ´success´ but that the creation really fails.

**Comment by zapodeanu** [comment]
I tested the API and it creates the subpool (Cisco DNA Center version 2.3.5.3):
Request Payload:

```
{
   "name": "LO_pool3",
   "type": "Generic",
   "ipv4GlobalPool": "10.1.0.0/16",
   "ipv4Prefix": true,
   "ipv4PrefixLength": 24,
   "ipv4Subnet": "10.1.11.0",
   "ipv4GateWay": "10.1.11.1",
   "ipv4DhcpServers": [
      "10.1.1.1"
   ],
   "ipv4DnsServers": [
      "10.1.1.1"
   ]
}
```

Execution id response:
```
{
    "bapiKey": "429f-aa81-4d3b-960a",
    "bapiName": "Reserve IP Subpool",
    "bapiExecutionId": "ea7a2bef-1bfd-4f82-b56d-1e3b2b6e3e9f",
    "startTime": "Tue Jun 27 23:01:49 UTC 2023",
    "startTimeEpoch": 1687906909128,
    "endTime": "Tue Jun 27 23:01:51 UTC 2023",
    "endTimeEpoch": 1687906911405,
    "timeDuration": 2277,
    "status": "SUCCESS",
    "bapiSyncResponse": "{\"name\":\"LO_pool3\",\"type\":\"generic\",\"result\":{\"startTime\":1687906909518,\"endTime\":1687906911188,\"progress\":\"Subpool Creation d6081dbb-b4d9-4521-b25d-e8ca3d466b3c\"},\"status\":\"True\"}",
    "runtimeInstanceId": "DNACP_Runtime_66d782df-528d-43e5-b142-ed349a095c3c"
}
```

**Comment by mschedrin** [comment]
It works correct in newer versions of DNAC and provider.
