### ISSUE TITLE
Error on successfull  creation of resource dnacenter_pnp_device_import

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#122]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When creating dnacenter_pnp_device_import resource, terraform returns error: 
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # dnacenter_pnp_device_import.this will be created
  + resource "dnacenter_pnp_device_import" "this" {
      + id           = (known after apply)
      + item         = (known after apply)
      + last_updated = (known after apply)

      + parameters {
          + payload {
              + device_info {
                  + hostname      = "test-sw02"
                  + pid           = "C9300-48U"
                  + serial_number = "dfdfsra1"
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
dnacenter_pnp_device_import.this: Creating...
╷
│ Error: Failure when setting ImportDevicesInBulk response
│ 
│   with dnacenter_pnp_device_import.this,
│   on sda_device.tf line 2, in resource "dnacenter_pnp_device_import" "this":
│    2: resource "dnacenter_pnp_device_import" "this" {
│ 
│ Invalid address to set: []string{"item", "0", "success_list", "0",
│ "type_id"}
╵
ERRO[0009] Terraform invocation failed in /home/admmikshc/dev/dnac/minilab/.terragrunt-cache/1CSNjBdg1GHoveoEP3oiGPPj3Lk/6dl3eRSK6XeLPjg17O2JEUtNu2k/dnac-sandbox  prefix=[/home/admmikshc/dev/dnac/minilab] 
ERRO[0009] 1 error occurred:
        * exit status 1
```
According to terraform debug log the resource has been successfully created, but the provider fails to parse DNAC response. 
 [tf.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10426344/tf.log)

**Expected behavior**
The provider is supposed to parse response from DNAC API without throwing error. 

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.6-70045
* Terraform version:1.3.6
* Cisco DNA Center provider version:1.0.15-beta
* OS Version: ubuntu 20.04.5

**Additional context**

**Comment by mschedrin** [comment]
There is the same issue with dnacenter_pnp_device.

**Comment by fmunozmiranda** [comment]
Hi @mschedrin  could you please try it again with new provider version (1.0.16-beta) and update us if it works.

**Comment by mschedrin** [comment]
Yes, it works now.
