### ISSUE TITLE
Provider crash when creating resource dnacenter_wireless_provision_ssid_create_provision

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#124]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Provider crashes when trying to create resource dnacenter_wireless_provision_ssid_create_provision. 
Resource definition:
```
resource "dnacenter_wireless_provision_ssid_create_provision" "this" {
  parameters {
    enable_fabric = true
    flex_connect {
      enable_flex_connect = false
    }
    managed_aplocations = ["Global/labhf/Skoyen/Floor2"]
    ssid_details {
      name          = "labhf"
      enable_broadcast_ssi_d                = true
      enable_fast_lane                      = false
      enable_mac_filtering                  = false
      fast_transition                       = "Adaptive"
      radio_policy                          = "Triple band operation (2.4GHz, 5GHz and 6GHz)"
      security_level                        = "WPA3_ENTERPRISE"
      traffic_type                          = "data"
    }
    ssid_type = "Enterprise"    
  }
}

```
Terraform output and debug log:
[tf_debug.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10436554/tf_debug.log)
[tf_output.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/10436555/tf_output.log)

**Expected behavior**
The provider is not supposed to crash.

**Screenshots**
Not relevant

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.6-70045
* Terraform version: 1.3.6
* Cisco DNA Center provider version: 1.0.15-beta
* OS Version: Ubuntu 20.04.5

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @mschedrin  could you please try it again with new provider version (1.0.16-beta) and update us if it works.

**Comment by mschedrin** [comment]
Provider does not crash any more. I still can't get resource to be created, but it seems that the problem is now on DNAC side. Thanks for quick fix.
