### ISSUE TITLE
data "dnacenter_site" - Failure when executing GetSite

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#155]
**Describe the bug**
data "dnacenter_site" - doesn't work after upgrade to 1.1.0-beta.  It works in 1.0.19-beta

```ruby 
data "dnacenter_site" "building" {
  provider = dnacenter
    for_each = var.reserve_ip_pool
    name = each.value.building
}

 output "dnacenter_site_building" {
 value = values(data.dnacenter_site.building)[*].items.0.id
}
```
**Expected behavior**
terraform init -upgrade                   

Initializing the backend...

Initializing provider plugins...
- Finding cisco-en-programmability/dnacenter versions matching "1.0.19-beta"...
- Installing cisco-en-programmability/dnacenter v1.0.19-beta...
- Installed cisco-en-programmability/dnacenter v1.0.19-beta (self-signed, key ID A3DE487CD358EC62)

 % terraform plan -var-file="ip_pools.tfvars"
data.dnacenter_site.building["Test_BorderWAN_Pegasus1"]: Reading...
data.dnacenter_site.building["Test3_BorderWAN_Pegasus1"]: Reading...
data.dnacenter_site.building["Test2_BorderWAN_Pegasus1"]: Reading...
data.dnacenter_site.building["Test2_BorderWAN_Pegasus1"]: Read complete after 0s [id=1681564772]
data.dnacenter_site.building["Test3_BorderWAN_Pegasus1"]: Read complete after 1s [id=1681564772]
data.dnacenter_site.building["Test_BorderWAN_Pegasus1"]: Read complete after 1s [id=1681564772]

Changes to Outputs:
  + dnacenter_site_building = [
      + "90f91e29-c1fd-4cc9-b19d-278f7fb9b3fa",
      + "d906815a-f735-4dff-8116-d49ab799d2f9",
      + "4186ff1b-e3ad-46a5-b82e-f522f305bafa",
    ]

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

───────────────────────────────────────────────────────────
 
 % terraform init -upgrade                   

Initializing the backend...

Initializing provider plugins...
- Finding cisco-en-programmability/dnacenter versions matching "1.1.0-beta"...
- Installing cisco-en-programmability/dnacenter v1.1.0-beta...
- Installed cisco-en-programmability/dnacenter v1.1.0-beta (self-signed, key ID A3DE487CD358EC62)

% terraform plan -var-file="ip_pools.tfvars"
data.dnacenter_site.building["Test2_BorderWAN_Pegasus1"]: Reading...
data.dnacenter_site.building["Test3_BorderWAN_Pegasus1"]: Reading...
data.dnacenter_site.building["Test_BorderWAN_Pegasus1"]: Reading...
╷
│ Error: Failure when executing GetSite
│ 
│   with data.dnacenter_site.building["Test3_BorderWAN_Pegasus1"],
│   on global_ip_pools.tf line 2, in data "dnacenter_site" "building":
│    2: data "dnacenter_site" "building" {
│ 
│ json: cannot unmarshal object into Go struct field ResponseSitesGetSiteResponse.response.additionalInfo of type string
╵
╷
│ Error: Failure when executing GetSite
│ 
│   with data.dnacenter_site.building["Test_BorderWAN_Pegasus1"],
│   on global_ip_pools.tf line 2, in data "dnacenter_site" "building":
│    2: data "dnacenter_site" "building" {
│ 
│ json: cannot unmarshal object into Go struct field ResponseSitesGetSiteResponse.response.additionalInfo of type string
╵
╷
│ Error: Failure when executing GetSite
│ 
│   with data.dnacenter_site.building["Test2_BorderWAN_Pegasus1"],
│   on global_ip_pools.tf line 2, in data "dnacenter_site" "building":
│    2: data "dnacenter_site" "building" {
│ 
│ json: cannot unmarshal object into Go struct field ResponseSitesGetSiteResponse.response.additionalInfo of type string

[debug-not-working.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11239631/debug-not-working.txt)
[debug-working.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11239632/debug-working.txt)

**Comment by fmunozmiranda** [comment]
hi @artur-tekieli , which version of DNA Center API are you using?

**Comment by artur-tekieli** [comment]
Hi @fmunozmiranda , It is DNA Center Version 2.3.3.7

**Comment by artur-tekieli** [comment]
Hi @fmunozmiranda yes it works for me now.
