### ISSUE TITLE
Cannot create a new area using dnacenter_site

### ISSUE THREAD

**Issue by asummerau** [cisco-en-programmability/terraform-provider-dnacenter#156]
**Prerequisites**

* [x] Have you tested the operation in the API directly? 
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When upgrading the Terraform provider to 1.1.0-beta it is no longer possible to create a new (non-existing) area using the resource dnacenter_site, as given below. Prior to 1.1.0-beta, it was possible to create a new area by using exactly this code. 
```terraform
resource "dnacenter_site" "subarea" {
  provider = dnacenter
  parameters {
    site {
      area {
        name = var.subarea_name
        parent_name = "${var.area_parent_name}/${var.area_name}"
      }
    }
  type = "area"
  }
}
```
With 1.1.0-beta, the error message appears telling that the "site_id" is missing. However, to create a new area, the id is not yet known and cannot be specified at this step. 
![Screenshot 2023-04-19 at 17 13 38](https://user-images.githubusercontent.com/119070318/233120867-57622870-5efe-43e8-88c7-79ac1c5d0e85.png)

**Expected behavior**
As in prior versions, this resource should create a new area when no "site_id" is specified. 

**Screenshots**
<img width="1038" alt="Screenshot 2023-04-19 at 16 59 12" src="https://user-images.githubusercontent.com/119070318/233116782-51417aa7-27bf-4a00-a156-261b5321bf23.png">

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.0
* Terraform version: 1.3.9
* Cisco DNA Center provider version: 1.1.0-beta
* OS Version: Ubuntu 22.04.1

**Additional context**
-

**Comment by fmunozmiranda** [comment]
Hi @asummerau please try it again with  v1.1.1-beta and let us know if it works for you.
