### ISSUE TITLE
Discrepancies in resource updates and documentation between provider versions 1.0.19 and 1.1.0

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#157]
I am writing to bring to your attention a significant discrepancy I've identified when comparing two versions of the 'provider.go' file, namely version 1.0.19 and version 1.1.0.

Upon close examination, it's evident that several resources and data sources have undergone additions, removals, or renamings between these versions. Specifically, numerous `dnacenter_global_credential_*` resources appear to have been removed, while a `dnacenter_global_credential_update` resource has been introduced in version 1.1.0.

My assumption is that the functionality of the removed resources has been transferred to the new `dnacenter_global_credential_update` resource. However, this change isn't reflected in the documentation for version 1.1.0. The documentation continues to list resources that were present in version 1.0.19 but are absent in the 1.1.0 version, without any indication of deprecation or relocation.

To rectify this situation, I kindly request you to update the documentation to accurately reflect the changes in resources between the two versions. It would be especially helpful for users like myself to have explicit references to the new resources that are replacing the old ones. This would greatly facilitate our understanding of the transitions and enable us to adapt our usage patterns accordingly.

Thank you for your attention to this matter. I look forward to your prompt response and the necessary updates to the documentation.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/9823462/234836283-7ad40804-2c48-43be-a506-3f6a884561c2.png">

**Comment by fmunozmiranda** [comment]
Hi @mschedrin  please try it again with v1.1.1-beta and let us know if it works for you.

**Comment by mschedrin** [comment]
Thank you. Resources are back.
