### ISSUE TITLE
Mandatory parameter `wireless_profile_name` for `dnacenter_wireless_profile` resource

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#160]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
`wireless_profile_name` parameter for `dnacenter_wireless_profile` resource is not mandatory in DNAC API and is not supposed to be required by dnacenter_wireless_profile.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/9823462/235708918-4ccb4dc9-e3a3-44a5-aba2-0a5ca7799d6f.png">

**Expected behavior**
`dnacenter_wireless_profile` parameter is not mandatory for resource `wireless_profile_name`. 

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.0-70586
* Terraform version: 1.3.6
* Cisco DNA Center provider version: 1.1.1-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
Hi @mschedrin, please try again with v1.1.2-beta terraform-provider-dnacenter and let us know how it goes.

**Comment by mschedrin** [comment]
Yes, it works, thank you.
