### ISSUE TITLE
Failure when refreshing state of `dnacenter_global_credential_cli` and `dnacenter_global_credential_netconf` resources

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#161]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Terraform returns error when refreshes state for `dnacenter_global_credential_cli` and `dnacenter_global_credential_netconf` resources. 

```
│ Error: Failure when setting GetGlobalCredentials search response
│ 
│   with dnacenter_global_credential_cli.this["Global_cli"],
│   on global_credentials.tf line 15, in resource "dnacenter_global_credential_cli" "this":
│   15: resource "dnacenter_global_credential_cli" "this" {
│ 
│ Invalid address to set: []string{"item", "0", "write_community"}
╵
╷
│ Error: Failure when setting GetGlobalCredentials search response
│ 
│   with dnacenter_global_credential_cli.this["Nesodden_cli"],
│   on global_credentials.tf line 15, in resource "dnacenter_global_credential_cli" "this":
│   15: resource "dnacenter_global_credential_cli" "this" {
│ 
│ Invalid address to set: []string{"item", "0", "secure"}
╵
╷
│ Error: Failure when setting GetGlobalCredentials search response
│ 
│   with dnacenter_global_credential_netconf.this["netconf"],
│   on global_credentials.tf line 43, in resource "dnacenter_global_credential_netconf" "this":
│   43: resource "dnacenter_global_credential_netconf" "this" {
│ 
│ Invalid address to set: []string{"item", "0", "read_community"}
╵
```

**Expected behavior**
State refresh should not fail.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.0-70586
* Terraform version: 1.3.6
* Cisco DNA Center provider version: 1.1.1-beta
* OS Version: Ubuntu 20.04

**Additional context**
Provider debug log [dnac-phase-01.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11375362/dnac-phase-01.log)

**Comment by fmunozmiranda** [comment]
Hi @mschedrin, please try again with v1.1.2-beta terraform-provider-dnacenter and let us know how it goes.

**Comment by mschedrin** [comment]
I still get the same error message with v1.1.2-beta.

**Comment by mschedrin** [comment]
Same error with v1.1.3-beta. 
[dnac-phase-01.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11430689/dnac-phase-01.log)
```
dnacenter_site_assign_credential.this["Global"]: Creating...
dnacenter_site_assign_credential.this["Global"]: Creation complete after 5s [id=1683631870]
╷
│ Error: Missing required argument
│ 
│   with dnacenter_site_assign_credential.this["Global/SUNHF/Nesodden"],
│   on global_credentials.tf line 57, in resource "dnacenter_site_assign_credential" "this":
│   57:     site_id = (
│   58:       each.key != "Global" ?
│   59:       try(local.merged_site_hierarchy[each.key].item[0].id, null) :
│   60:     data.dnacenter_site.global.items[0].id)
│ 
│ The argument "parameters.0.site_id" is required, but no definition was found.
╵
```

**Comment by mschedrin** [comment]
Works with v1.1.6-beta.
