### ISSUE TITLE
dnacenter_sda_fabric_authentication_profile - Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#162]
**Describe the bug**
In version 1.1.1-beta
dnacenter_sda_fabric_authentication_profile - gives "Error: Provider produced inconsistent result after apply"

It is working fine with version 1.0.19-beta.

**Screenshots**
![Screenshot 2023-05-02 at 18 17 48](https://user-images.githubusercontent.com/106110026/235726103-cc314056-09d2-4ddc-8788-adf1399c7446.png)

**Environment (please complete the following information):**
* Cisco DNA Center version and patch:  2.3.3.7
* Terraform version: 1.4.6
* Cisco DNA Center provider version: 1.1.1-beta
* OS Version: macos 13.3.1

[tf_debug.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11375469/tf_debug.txt)

**Comment by fmunozmiranda** [comment]
Hi @artur-tekieli , please try again with v1.1.2-beta terraform-provider-dnacenter and let us know how it goes.
