### ISSUE TITLE
Provider produced inconsistent result after apply while creating `dnacenter_global_pool`

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#164]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Following error is returned when creating `dnacenter_global_pool`:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to dnacenter_global_pool.this["100.69.0.0_16"], provider "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]" produced an unexpected new value: Root
│ resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Expected behavior**
Resource is created without errors. 

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.0-70586
* Terraform version: 1.3.6
* Cisco DNA Center provider version: 1.1.1-beta
* OS Version: Ubuntu 20.04

**Additional context**
Debug log [dnac-phase-01.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11375719/dnac-phase-01.log)

**Comment by fmunozmiranda** [comment]
Hi @mschedrin, please try again with v1.1.2-beta terraform-provider-dnacenter and let us know how it goes.

**Comment by mschedrin** [comment]
Works correct now.
