### ISSUE TITLE
Failure when executing AddVnInFabric 

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#167]
**Describe the bug**
When applying `resource` `dnacenter_sda_virtual_network` in version 1.1.2-beta - 
It fails with **"Failure when executing AddVnInFabric"**

It works in 1.0.19-beta - with but with: `payload {}`
In 1.1.2-beta - seems: `payload {}` , is no longer required 

**Expected behavior**
VN should be added to Fabric Site.

**Screenshots**
![Screenshot 2023-05-04 at 16 20 28](https://user-images.githubusercontent.com/106110026/236236129-6e2cdb3c-dcc2-42c1-8c9e-dd912e9fb9a7.png)

**Environment (please complete the following information):**
* Cisco DNA Center version and patch:  2.3.3.7
* Terraform version: 1.4.6
* Cisco DNA Center provider version: 1.1.2-beta
* OS Version: macos 13.3.1

**Additional context**
[tf_debug.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11398452/tf_debug.txt)

**Comment by fmunozmiranda** [comment]
hi @artur-tekieli please try it again with latest version.

**Comment by artur-tekieli** [comment]
this is resolved.
