### ISSUE TITLE
Local state of `Authenticate Template` not updated 

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#176]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
After deployment of `dnacenter_sda_fabric_authentication_profile` with `authenticate_template_name  = "Closed Authentication"` And then manually changing the Authentication Template on DNAC to "none" 
thereafter executing `terraform plan` or `terraform apply` terraform never learns the change done on DNAC and keeps the `authenticate_template_name  = "Closed Authentication"` 

**Expected behavior**
I would expect terraform to refresh the local state to `No Authentication` as per the API output.

**Screenshots**
API is working:
![Screenshot 2023-05-10 at 18 26 28](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/106110026/4ca9c252-3a1c-4bde-b615-4c8b2b56a93c)

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.3.7
* Terraform version: 1.4.6
* Cisco DNA Center provider version: 1.1.6-beta
* OS Version: MacOS 13.3.1

**Additional context**
[apply.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11444489/apply.txt)
[terraform.tfstate.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11444494/terraform.tfstate.txt)

**Comment by fmunozmiranda** [comment]
Hi, @artur-tekieli  

I tried to help you with the problem, let me know if it works for you now..

However, this type of problem can be very common in the provider due to the non-idempotency of the API.

**Comment by mschedrin** [comment]
@fmunozmiranda can you please elaborate what are the issues with the API that makes it to impossible to read resource from DNAC and update local state? We should probably report to Cisco BU in order to get API fixed. @zapodeanu

**Comment by wastorga** [comment]
I think it was https://github.com/cisco-en-programmability/terraform-provider-dnacenter/issues/189#issuecomment-1658728102

**Comment by wastorga** [comment]
The new Terraform provider for dnacenter is up, v1.1.10-beta.

The new version has several changes that affect the resource dnacenter_sda_fabric_authentication_profile:
- Patches the response struct for the get operation of the sda_fabric_authentication_profile resource.
- Fixes business execution status verification for this resource

Please, try again with the new version.

**Comment by wastorga** [comment]
I recommend you upgrade DNA Center to a newer release, at least for the following reasons.

- There have been multiple improvements and fixes in DNA Center APIs
- Our Terraform provider "dnacenter" development effort moves towards supporting the last DNA Center versions on the Compatibility Matrix (for now, 2.3.5.3) rather than those below.

**Comment by fmunozmiranda** [comment]
@artur-tekieli update us if it works now, or ticket is going to be closed in next 24 hours due inactivity.
