### ISSUE TITLE
DNAC-Floor creation issue 

### ISSUE THREAD

**Issue by Balajipublic008** [cisco-en-programmability/terraform-provider-dnacenter#186]
**Prerequisites**
* [x] Have you tested the operation in the API directly?             yes
* [x] Do you have the latest Terraform provider version?            yes
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
task is to create a new floor into to the existing building(dnacenter_site) when i do the validation and plan there is no error, but when i click apply i am getting the error. 

**Expected behavior**
It should provision new floor into the existing building as per the terraform documentation 

**Screenshots**
![image](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/118354238/f6f75ecf-5f5a-42fa-a826-424d549f588d)

**Environment (please complete the following information):**
* Cisco DNA Center version and patch:         Version 2.2.3.6
* Terraform version:                                       latest version 1.5.1
* Cisco DNA Center provider version:           latest version 1.1.8-beta
* OS Version:                                                 Windows 11

**Additional context**
dnacenter_site.Floor_2: Creating...
╷
│ Error: Plugin did not respond
│
│   with dnacenter_site.Floor_2,
│   on new_site.tf line 5, in resource "dnacenter_site" "Floor_2":
│    5: resource "dnacenter_site" "Floor_2" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.   
╵

Stack trace from the terraform-provider-dnacenter_v1.1.8-beta.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x1d9e8b7]

goroutine 14 [running]:
terraform-provider-dnacenter/dnacenter.resourceSiteCreate({0x235f888, 0xc00081bd70}, 0x0?, {0x1fb2100?, 0xc00054a160?})
        terraform-provider-dnacenter/dnacenter/resource_site.go:316 +0xc17
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00018c8c0, {0x235f8c0, 0xc0005235f0}, 0xd?, {0x1fb2100, 0xc00054a160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00018c8c0, {0x235f8c0, 0xc0005235f0}, 0xc00052c340, 0xc000ea5780, {0x1fb2100, 0xc00054a160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00039eea0, {0x235f8c0?, 0xc0005234d0?}, 0xc000a6fa40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000256000, {0x235f8c0?, 0xc000522330?}, 0xc0010dea80)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x20888a0?, 0xc000256000}, {0x235f8c0, 0xc000522330}, 0xc0010dea10, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002541e0, {0x2363398, 0xc000842000}, 0xc000b9e360, 0xc0009f0240, 0x2a68f60, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0002541e0, {0x2363398, 0xc000842000}, 0xc000b9e360, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-dnacenter_v1.1.8-beta.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by Balajipublic008** [comment]
Hi Team,
Eagerly waiting for your reply. Please respond.

**Comment by fmunozmiranda** [comment]
hey @Balajipublic008 did you try @mschedrin's suggestion?

Update us how does it go.

**Comment by fmunozmiranda** [comment]
Closed due inacticity.
