### ISSUE TITLE
Error when creating `dnacenter_sda_fabric_authentication_profile`

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#189]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Terraform returns error when creating `dnacenter_sda_fabric_authentication_profile`:
```
Plan: 9 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vns = (sensitive value)
dnacenter_sda_fabric_authentication_profile.this["Global/MINIHF/OSL"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to dnacenter_sda_fabric_authentication_profile.this["Global/MINIHF/OSL"], provider "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]" produced an unexpected new value: Root resource was
│ present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Expected behavior**
No error is expected.

**Screenshots**
Not relevant.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.3
* Terraform version: 1.5.0
* Cisco DNA Center provider version: 1.1.8-beta
* OS Version: Ubuntu 20.04

**Additional context**
According to logs it seems there is type error when parsing API reply:
`2023-07-12T12:45:18.158+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.8-beta: 2023/07/12 12:45:18 [ERROR] [RESTY] json: cannot unmarshal bool into Go struct field ResponseSdaGetDefaultAuthenticationProfileFromSdaFabric.wakeOnLan of type string, Attempt 1: timestamp=2023-07-12T12:45:18.157+0200`

Check out [dnac.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12027083/dnac.log) for more details.

**Comment by mschedrin** [comment]
The issue is present in 1.1.9-beta too, @fmunozmiranda.

**Comment by mschedrin** [comment]
Perhaps @wastorga would be so kind to check this issue?

**Comment by wastorga** [comment]
From what I see from the logs

```
2023-07-12T12:45:18.158+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.8-beta: 2023/07/12 12:45:18 [ERROR] [RESTY] json: cannot unmarshal bool into Go struct field ResponseSdaGetDefaultAuthenticationProfileFromSdaFabric.wakeOnLan of type string, Attempt 1: timestamp=2023-07-12T12:45:18.157+0200
```

There is something wrong with the type of the property wakeOnLan. 
Its type is both a string (empty string) and a boolean in the DNAC actual API responses, depending on the authenticateTemplateName, so changing it back to documentation boolean will still yield errors.

I'm working on a patch. However this should be really solved in DNA Center API instead.

**Comment by wastorga** [comment]
Related issues
https://github.com/cisco-en-programmability/terraform-provider-dnacenter/issues/176
https://github.com/cisco-en-programmability/terraform-provider-dnacenter/issues/127

**Comment by wastorga** [comment]
The new Terraform provider for dnacenter is up, v1.1.10-beta.

The new dnacenter provider version has several changes that affect the resource dnacenter_sda_fabric_authentication_profile:
- It patches the response struct for the get operation of the sda_fabric_authentication_profile resource.
- It fixes business execution status verification for this resource

Please, try again with the new version.
