### ISSUE TITLE
tag resource

### ISSUE THREAD

**Issue by robertcsapo** [cisco-en-programmability/terraform-provider-dnacenter#2]
Hey,

Certain elements for [resourceTag](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/blob/2cb6755dbe1432b610db363d85c08732979171f2/dnacenter/resource_dna_tag.go#L13) isn't matching the Cisco DNA Center Platform API.

Fields that should be ```Optional``` and not ```Required```
- description
- system_tag
- instance_tenant_id

### Terraform Version
```
terraform -v           
Terraform v0.14.9
```

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_dna_tag.go 

### Terraform Configuration Files
```hcl
resource "dna_tag" "tf_tag" {
  provider = dnacenter
  item {
    system_tag = false
    description = "Terraform Tag"
    name = "Terraform"
  }
}
```

### Debug Output
```
Error: Missing required argument

  on main.tf line 60, in resource "dna_tag" "data":
  60:   item {

The argument "instance_tenant_id" is required, but no definition was found.
```

### Steps to Reproduce
1. `terraform plan`

### Workaround
Set a dummy value for ```instance_tenant_id```
```hcl
resource "dna_tag" "tf_tag" {
  provider = dnacenter
  item {
    system_tag = false
    description = "Terraform Tag"
    name = "Terraform"
    instance_tenant_id = ""
  }
}
```

### References
https://developer.cisco.com/docs/dna-center/#!create-tag

**Comment by wastorga** [comment]
The latest version, 0.0.4, addressed this issue.

**Comment by wastorga** [comment]
Feel free to reopen if the problem still exists. Thank you.
