### ISSUE TITLE
In-place update of resource `dnacenter_configuration_template_version` does not do anything with API

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#212]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Creation and deletion of resource `dnacenter_configuration_template_version` works right, but once I need to change the resource no requests to DNAC API are being sent. 
Output of `terraform apply` command:
```
data.dnacenter_configuration_template_project.all: Reading...
data.dnacenter_configuration_template_project.all: Read complete after 0s [id=1695747072]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # dnacenter_configuration_template_version.this will be updated in-place
  ~ resource "dnacenter_configuration_template_version" "this" {
        id   = "template_id:=3e02dfb5-d67d-4f49-a331-79fdcdc401a9"
        # (1 unchanged attribute hidden)

      ~ parameters {
          ~ comments    = "9003" -> "9004"
            # (1 unchanged attribute hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
dnacenter_configuration_template_version.this: Modifying... [id=template_id:=3e02dfb5-d67d-4f49-a331-79fdcdc401a9]
dnacenter_configuration_template_version.this: Modifications complete after 0s [id=template_id:=3e02dfb5-d67d-4f49-a331-79fdcdc401a9]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
Terraform debug log: [dnac.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12730100/dnac.sanitized.log)

**Expected behavior**
The resource should send POST request with new payload. 

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.17-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
![image](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/93611708/0e8446e8-5c4f-44fc-aa71-83efc892ace3)
According to the documentation, there is no UPDATE method for this resource, we are working on providing an error message for these cases, in order to avoid confusion.

**Comment by fmunozmiranda** [comment]
Ah error message was include to avoid confusions.
