### ISSUE TITLE
Resource `dnacenter_reserve_ip_subpool` does not detect changes made outside terraform

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#217]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
I have changed dhcpServerIps parameter in DNAC outside of terraform. When running terraform apply it does not detect changed values and does not update the resource. 

**Expected behavior**
Changes are detected during state refresh and corrected during apply procedure.

**Screenshots**
Reserved ip subpool configuration from DNAC: 
<img width="562" alt="image" src="https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/9823462/f982d705-f055-4d1e-9af1-b5603cb83970">
Terraform state for the same ip subpool:
<img width="596" alt="image" src="https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/9823462/c76006e6-2f04-4fbf-888e-6038c79bd870">
Terrarom  apply output: 
<img width="1688" alt="image" src="https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/9823462/eb107f3d-ba4f-428e-bc56-fe8c0e7b5600">

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.17-beta
* OS Version: Ubuntu 20.04

**Comment by mschedrin** [comment]
@fmunozmiranda @zapodeanu do you need any extra inputs regarding this issue?

**Comment by fmunozmiranda** [comment]
Hi @mschedrin , could you please send me logs of tf_provider.
Specially I want to see your request body for create, and response given from Get.
Thanks.

**Comment by mschedrin** [comment]
@fmunozmiranda here is the log where terraform creates new reserved pool named "test2" 
[dnac.create_reserved_pool.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13045944/dnac.create_reserved_pool.sanitized.log)


After that I have added additional dhcp server to reserverd ip pool "test2" and ran `terraform apply` again. It should have detected new dhcp server, but it didn't happen. Log: 
[dnac.detect_changed_reserved_pool.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13045949/dnac.detect_changed_reserved_pool.sanitized.log)

**Comment by fmunozmiranda** [comment]
Hi @mschedrin please test it with new version, if there is some change is not detected, please update me.

**Comment by edudppaz** [comment]
Hi @fmunozmiranda , writin for mschedrin here:

after updating to 1.1.26, the resource is now trying to apply changes to the ip pools , but failing (as updating ip pools already reserved is not possible on DNAC).
This happens on each apply. Even if we completely remove the pool reservation and create it from scratch with the new version, the next apply tries to push the dhcp_servers and prefix_length again. So it seems like the data read back from DNAC is not properly being stored on the state


```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 
Terraform will perform the following actions:
 
  # dnacenter_reserve_ip_subpool.this["devhf_SVG_medtek_vlan855"] will be updated in-place
  ~ resource "dnacenter_reserve_ip_subpool" "this" {
        id   = "name:=devhf_SVG_medtek_vlan855\\site_id:=096494e8-3f32-4f27-9a17-2c670da2ee9e"
        # (1 unchanged attribute hidden)
 
      ~ parameters {
          ~ ipv4_dhcp_servers  = [
              + "100.68.0.141",
            ]
          ~ ipv4_prefix_length = 0 -> 23
            name               = "devhf_SVG_medtek_vlan855"
            # (12 unchanged attributes hidden)
        }
    }
 
Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
dnacenter_reserve_ip_subpool.this["devhf_SVG_medtek_vlan855"]: Modifying... [id=name:=devhf_SVG_medtek_vlan855\site_id:=096494e8-3f32-4f27-9a17-2c670da2ee9e]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command
│ to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to
│ use it as part of an error message.
╵
╷
│ Error: Failure when executing UpdateReserveIPSubpool
│ 
│   with dnacenter_reserve_ip_subpool.this["devhf_SVG_medtek_vlan855"],
│   on ip_pools.tf line 45, in resource "dnacenter_reserve_ip_subpool" "this":
│   45: resource "dnacenter_reserve_ip_subpool" "this" {
│

```

This is the data stored on the state:

```
                    dhcp_server_ips         = [
                        "\"100.68.0.141\"",
                    ]
                    
```
There is no data in the state for ipv4_prefix_length . These errors might be relevant:

```

2023-11-15T22:06:16.774+0100 [WARN]  Provider "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]" produced an unexpected new value for dnacenter_reserve_ip_subpool.this["devhf_SVG_medtek_vlan855"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .parameters[0].id: was null, but now cty.StringVal("")
      - .parameters[0].ipv4_dhcp_servers: element 0 has vanished
      - .parameters[0].ipv4_prefix_length: was cty.NumberIntVal(23), but now cty.NumberIntVal(0)
      ```

**Comment by mschedrin** [comment]
Changes outside terraform are now detected, however update operation on `dnacenter_reserve_ip_subpool` stopped working. It generates unexpected parameters that DNAC API does not accept. 
Output from terraform plan:
```
Terraform will perform the following actions:

  # dnacenter_reserve_ip_subpool.this["devhf_OSL_admtek_v713_1"] will be updated in-place
  ~ resource "dnacenter_reserve_ip_subpool" "this" {
        id   = "name:=devhf_OSL_admtek_v713_1\\site_id:=347b65cb-256d-40da-9a20-cd6d1d0d6a83"
        # (1 unchanged attribute hidden)

      ~ parameters {
          ~ ipv4_dhcp_servers  = [
                "100.68.0.141",
              - "1.1.1.1",
            ]
            name               = "devhf_OSL_admtek_v713_1"
            # (13 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
dnacenter_reserve_ip_subpool.this["devhf_OSL_admtek_v713_1"]: Modifying... [id=name:=devhf_OSL_admtek_v713_1\site_id:=347b65cb-256d-40da-9a20-cd6d1d0d6a83]
╷
│ Error: Failure when executing UpdateReserveIPSubpool
│ 
│   with dnacenter_reserve_ip_subpool.this["devhf_OSL_admtek_v713_1"],
│   on ip_pools.tf line 45, in resource "dnacenter_reserve_ip_subpool" "this":
│   45: resource "dnacenter_reserve_ip_subpool" "this" {
│ 
╵

```

Body that the provider has created:
```
PUT  /dna/intent/api/v1/reserve-ip-subpool/347b65cb-256d-40da-9a20-cd6d1d0d6a83?id=bb6c8f7b-4002-4a4e-baa8-6d15820116f0  HTTP/1.1
BODY   :
{
   "name": "devhf_OSL_admtek_v713_1",
   "ipv4DhcpServers": [
      "100.68.0.141"
   ],
   "ipv6PrefixLength": 0,
   "ipv6TotalHost": 0,
   "ipv4GateWay": "10.134.66.1"
}
```
Parameters `ipv6PrefixLength`, `ipv6TotalHost`, `ipv4GateWay` are not supposed to be added to BODY.

**Comment by fmunozmiranda** [comment]
Hi @mschedrin  could you please say me what parameters are allowed in PUT?

**Comment by fmunozmiranda** [comment]
@mschedrin try it now with 1.1.28-beta please. Update parameters where updated.

**Comment by fmunozmiranda** [comment]
I'm going to close issue as successfully, if there's something else we can do here, please re-open it.
