### ISSUE TITLE
Provider does not handle authentication token expiration during terraform apply

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#221]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
If terraform apply takes significant time authentication token expires and provider crashes. Take a look in the logs.
[dnac.token_expired.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/12848252/dnac.token_expired.sanitized.log)

**Expected behavior**
Provider should renew token when it expires. 

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.21
* OS Version: Ubuntu 20.04

**Comment by mschedrin** [comment]
@bvargasre thanks for fixing it. Will I be able to see token expiration in terraform debug log or is reauthentication handled in SDK and "invisible" for the provider? I am not sure how long it takes authentication token to expire and therefore can not define successful test scenario. Do you have any information regarding expiration timer?

**Comment by gz06** [comment]
@mschedrin  The token expiration is 60 minutes, as documented in the API docs.

**Comment by zapodeanu** [comment]
@mschedrin The token expiration is 60 minutes, as documented in the API docs.

**Comment by mschedrin** [comment]
Thanks @zapodeanu, @bvargasre. I have ran a terraform apply job that went on for 75 minutes and can confirm that reauthentication works.
