### ISSUE TITLE
Hardcoded sleep in `dnacenter_floor`, `dnacenter_building`, `dnacenter_area`  resources

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#227]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
I noticed that deletion of `dnacenter_floor` resource is taking long time, looked at the resource code and found `time.Sleep(1 * time.Minute)` in `resourceFloorDelete` function. The same sleep can be found in `_building` and `_area` resources.  Please remove it, I hope it is not necessary any more.

**Comment by fmunozmiranda** [comment]
Hi @mschedrin, problem we are working to remove it, tommorow a new version will be released.

**Comment by mschedrin** [comment]
@fmunozmiranda you have removed delay in `building` resource, but forgot to do the same for `area`: https://github.com/cisco-en-programmability/terraform-provider-dnacenter/blob/860d4589a2bbaa683f3649f80c38579e0d3e2e1d/dnacenter/resource_area.go#L408 and `floor`: https://github.com/cisco-en-programmability/terraform-provider-dnacenter/blob/860d4589a2bbaa683f3649f80c38579e0d3e2e1d/dnacenter/resource_floor.go#L568

**Comment by fmunozmiranda** [comment]
Sleeps removed.
