### ISSUE TITLE
Provider crash when creating `dnacenter_reserve_ip_subpool` resource.

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#228]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Provider crashed when it was creating `dnacenter_reserve_ip_subpool` resource. Here is debug log: 
[dnac.sanitized.log.zip](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13050997/dnac.sanitized.log.zip)

Truncated terraform output:
```
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Creating...
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [10s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [20s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [30s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [40s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [50s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Still creating... [1m0s elapsed]
dnacenter_reserve_ip_subpool.this["generated_pool_189"]: Creation complete after 1m7s [id=name:=generated_pool_189\site_id:=ad1a9872-b0fb-4406-ba66-f7a8d9220215]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ dnacenter_reserve_ip_subpool.this["generated_pool_101"], provider
│ "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```
**Expected behavior**
No crash

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.23-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
Hi @mschedrin , your config is failing because of this:
![image](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/93611708/ef0cc84b-1adb-426b-846b-33018b990ff6)


I'm going to work, to capture the error, because for Terraform `status = success` means that resource was succesfully created but in this case it fails with status success.

**Comment by fmunozmiranda** [comment]
Please try it with new version, v1.1.24-beta. @mschedrin

**Comment by mschedrin** [comment]
It works.
