### ISSUE TITLE
`dnacenter_wireless_profiles` does not properly read or synchronizes to state

### ISSUE THREAD

**Issue by edudppaz** [cisco-en-programmability/terraform-provider-dnacenter#233]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
After pushing a new profile with `dnacenter_wireless_profiles` resource, and assigning SSIDs to this profile, if an operator does changes manually in dna center, a subsequent plan/apply does not see any changes between whats configured on DNAC and whats on the tfstate.

Examples:
- Removing an SSID manually from the profile (via GUI) and triggering a new plan, does not trigger any change on terraform
- Changing a SSID setting (like fabric enabled) on the profile (via GUI) and triggering a new plan, does not trigger any change on terraform

**Expected behavior**
Manual changes on the infrastructure done manually, should be seen by terraform as a deviation against the desired state and changes/reapply/etc should be made by terraform.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
Cisco DNA Center version and patch: 2.3.5.4 - 70852
Terraform version: 1.5.6
Cisco DNA Center provider version: 1.1.22-beta
OS Version: Ubuntu

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @edudppaz , please try it with new version and let us know if it works for you.

**Comment by edudppaz** [comment]
Hi @fmunozmiranda . Seems like the dnacenter_wireless_profiles resoure now detect changes on the infrastructure, but it also triggers changes on all the SSIDs (even if they have not been changed) and even removes configuration.
On the example below, i changed an SSID (eduroam) to "non-fabric" mode. terraform detected the change, but also removed all associated sites from the profile.

```
# dnacenter_wireless_profile.this["Wireless_devhf"] will be updated in-place
  ~ resource "dnacenter_wireless_profile" "this" {
        id   = "name:=Wireless_devhf"
        # (1 unchanged attribute hidden)
 
      ~ parameters {
          ~ profile_details {
                name  = "Wireless_devhf"
              ~ sites = [
                  - "Global/devhf/SVG",
                    "Global/devhf",
                  - "Global/devhf/SVG/Main Building",
                  - "Global/devhf/OSL",
                  - "Global/devhf/OSL/Main Building/Floor 1",
                  - "Global/devhf/SVG/Main Building/Floor 1",
                  - "Global/devhf/OSL/Main Building/Floor 2",
                  - "Global/devhf/OSL/Main Building",
                  - "Global/devhf/SVG/Main Building/Floor 2",
                ]
 
              ~ ssid_details {
                  ~ name          = "eduroam" -> "Gjest"
                    # (1 unchanged attribute hidden)
 
                    # (1 unchanged block hidden)
                }
              ~ ssid_details {
                  ~ name          = " Wireless" -> "IoT"
                    # (1 unchanged attribute hidden)
 
                    # (1 unchanged block hidden)
                }
              ~ ssid_details {
                  ~ name          = " IoT" -> "Wireless"
                    # (1 unchanged attribute hidden)
 
                    # (1 unchanged block hidden)
                }
              ~ ssid_details {
                  ~ enable_fabric  = "false" -> "true"
                  ~ name           = " Gjest" -> "eduroam"
                    # (1 unchanged attribute hidden)
 
                    # (1 unchanged block hidden)
                }
 
                # (1 unchanged block hidden)
            }
        }
    }
```

**Comment by fmunozmiranda** [comment]
Hi @edudppaz, could you please send me provider DEBUG logs? Thanks

**Comment by edudppaz** [comment]
Hi @fmunozmiranda , the logs have been shared with you via email

**Comment by fmunozmiranda** [comment]
Try with the new provider version, try to include all the ssidDetails that belong to the profile because otherwise they will be overwritten. When including a new one, place it last to avoid so many changes. Regarding sites, if you only place one site in the tf file and it has one assigned, Terrform will try to overwrite it with what is placed in the file, that is why it is eliminating sites, I recommend placing them all to avoid this problem.

Stay tuned.

**Comment by edudppaz** [comment]
> Try with the new provider version, try to include all the ssidDetails that belong to the profile because otherwise they will be overwritten. When including a new one, place it last to avoid so many changes. Regarding sites, if you only place one site in the tf file and it has one assigned, Terrform will try to overwrite it with what is placed in the file, that is why it is eliminating sites, I recommend placing them all to avoid this problem.
> 
> Stay tuned.
> 
> @edudppaz 

Hi @fmunozmiranda , the problem with the sites is that is a hierarchy.

So, choosing a higher level site, automatically chooses all sites below it on DNAC. In order to push complete list on every run, we would have to read all sites from dnac before each apply.

On previous versions (pre 1.1.24) this was working fine, but changed on 1.1.24+

**Comment by edudppaz** [comment]
Hi.
Seems like the SSID details under wireless_profiles bug is solved in 1.1.26-beta, however, the resource still does not properly configures the sites [] when the site is a higher level site in the hierarchy. (as. seen on my first post)

**Comment by edudppaz** [comment]
Hi @fmunozmiranda  , as informed via email, the issue with reading and synchonizing state is solved with 1 caveat:
If we use a "root" site on the hierarchy and assign it to the wireless profile, the site is assigned on the first apply, however changes to the assigned sites outside terraform are not detected by the resource.

**Comment by fmunozmiranda** [comment]
Main issue solved.
