### ISSUE TITLE
`dnacenter_wireless_rf_profile` does not properly read or synchronizes to state

### ISSUE THREAD

**Issue by edudppaz** [cisco-en-programmability/terraform-provider-dnacenter#234]
**Prerequisites**
* [ x] Have you tested the operation in the API directly?
* [ x] Do you have the latest Terraform provider version?
* [ x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
After pushing a new rf profile with `dnacenter_wireless_rf_profile` resource, if an operator does changes manually in dna center (like changing radio settings, 2,4/5g/6g settings, frequencies, etc), a subsequent plan/apply does not see any changes between whats configured on DNAC and whats on the tfstate.

Examples:
- Manually removing channels that were previous configured via terraform, does not trigger any change on tfapply/plan
- Disabling/Enabling radio types manually on DNAC, does not trigger any change on tfapply/plan even if the tfstate differs from the configuration

**Expected behavior**
Manual changes on the infrastructure done manually, should be seen by terraform as a deviation against the desired state and changes/reapply/etc should be made by terraform.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
Cisco DNA Center version and patch: 2.3.5.4 - 70852
Terraform version: 1.5.6
Cisco DNA Center provider version: 1.1.22-beta
OS Version: Ubuntu

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @edudppaz , for this, I would appreciate if you can pass me a request and response body example.

**Comment by edudppaz** [comment]
> Hi @edudppaz , for this, I would appreciate if you can pass me a request and response body example.

No change. Manually changing the settings on the RF_profile does not trigger a terraform change. Only the fully deletion of the profile triggers a re-apply

**Comment by fmunozmiranda** [comment]
@edudppaz ?

**Comment by edudppaz** [comment]
> @edudppaz ?

Hi @fmunozmiranda , do you need a request/response example from the API or an output from the terraform resource ?

**Comment by fmunozmiranda** [comment]
If You can pass me both it's better.

Thanks.

**Comment by edudppaz** [comment]
Information sent via email after webex.

**Comment by fmunozmiranda** [comment]
Closed due inactivity.
