### ISSUE TITLE
Provider crashes when creating resource `dnacenter_network_v2`

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#246]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Provider crashes upon creation of `dnacenter_network_v2`
```
dnacenter_network_v2.this["Global"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to dnacenter_network_v2.this["Global"], provider "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]" produced an unexpected new
│ value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
See attached debug [dnac.sanitized.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13503372/dnac.sanitized.log)

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852-HF3
* Terraform version: 1.6.3
* Cisco DNA Center provider version: 1.1.30-beta
* OS Version: Ubuntu 20.04

**Comment by fmunozmiranda** [comment]
Bug fixed. Try it and let me know how does it go.
The problem was with the `value` attribute as it is not consistent in type and value.

## Note
**With this resource we cannot detect changes made from outside the provider since we do not have enough data in the Read of the resource.**

**Comment by mikhail-shchedrin** [comment]
@fmunozmiranda it works now. Regarding your note about API READ method missing necessary data. Can you please elaborate what fields you are missing? I am going to create a bug report for DNA Center and refer this issue.

**Comment by mschedrin** [comment]
@fmunozmiranda it works now. Regarding your note about API READ method missing necessary data. Can you please elaborate what fields you are missing? I am going to create a bug report for DNA Center and refer this issue.

**Comment by fmunozmiranda** [comment]
## Request
```json
{
    "settings": {
        "dnsServer": {
            "domainName": "can only contain alphanumeric characters or hyphen",
            "primaryIpAddress": "valid range : 1.0.0.0 - 223.255.255.255",
            "secondaryIpAddress": "valid range : 1.0.0.0 - 223.255.255.255"
        },
        "network_aaa": {
            "servers": "Server type supported by ISE and AAA",
            "ipAddress": "Mandatory for ISE servers and for AAA consider this as additional IP.",
            "network": "For AAA server consider it as primary IP and For ISE consider as Network",
            "sharedSecret": "Supported only by ISE Servers"
        },
        "clientAndEndpoint_aaa": {
            "ipAddress": "Mandatory for ISE servers.",
            "sharedSecret": "Supported only by ISE servers"
        }
    }
   ```

## Response
```json
{
    "response": [
        {
            "instanceType": "string",
            "instanceUuid": "string",
            "namespace": "string",
            "type": "string",
            "key": "string",
            "version": 0,
            "value": [ "string" ],
            "groupUuid": "string",
            "inheritedGroupUuid": "string",
            "inheritedGroupName": "string"
        }
    ]
}
```

As you can see request a response body are totally different, that's why we cannot manage external changes.

Closing this issue cause is complete.
