### ISSUE TITLE
Provider crashes when creating areas

### ISSUE THREAD

**Issue by jschingen** [cisco-en-programmability/terraform-provider-dnacenter#250]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Our plan creates all 1200 locations in DNAC by creating a hierarchy of areas: region -> country -> state -> city
Example data: [dummy_site_data.json](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13665250/dummy_site_data.json)
Our plan that crashed was doing 4428 adds. We create the areas one level at a time. It crashed when creating countries.

**Expected behavior**
The plan runs successfully, as it did in our tests, for the whole dataset.

**Screenshots**
```
Stack trace from the terraform-provider-dnacenter_v1.1.31-beta plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x68 pc=0x1053a1878]

goroutine 14123 [running]:
terraform-provider-dnacenter/dnacenter.resourceAreaCreate({0x105d16208, 0x140015928a0}, 0x0?, {0x105bd9aa0?, 0x14000cfe160?})
	terraform-provider-dnacenter/dnacenter/resource_area.go:224 +0x978
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140000997a0, {0x105d16240, 0x14000ebd470}, 0xd?, {0x105bd9aa0, 0x14000cfe160})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000997a0, {0x105d16240, 0x14000ebd470}, 0x14000a3c8f0, 0x14001130e00, {0x105bd9aa0, 0x14000cfe160})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0x898
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000c048, {0x105d16240?, 0x14000ebd350?}, 0x140007f3950)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002d00a0, {0x105d16240?, 0x14000ebcb10?}, 0x14000bbefc0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105caf160?, 0x140002d00a0}, {0x105d16240, 0x14000ebcb10}, 0x14000bbef50, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002ce1e0, {0x105d18f20, 0x14000aa8340}, 0x14000bdf680, 0x14000a7ca80, 0x1063e2560, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xca0
google.golang.org/grpc.(*Server).handleStream(0x140002ce1e0, {0x105d18f20, 0x14000aa8340}, 0x14000bdf680, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x170

Error: The terraform-provider-dnacenter_v1.1.31-beta plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.6.4
* Cisco DNA Center provider version: 1.1.31-beta
* OS Version: MacOS 13.5.1

**Additional context**
Code snippet:
```
resource "dnacenter_area" "region" {
  for_each = {for u in var.sites : u.SITE_ID => u}
  provider = dnacenter
  parameters {
  type = "area"
    site {
      area {
        name        = each.value.REGION
        parent_name = "Global"
      }
    }
  }
}

resource "dnacenter_area" "country" {
  for_each = { for u in var.sites : u.HELIX_SITE_ID => u }
  provider = dnacenter
  parameters {
    type = "area"
    site {
      area {
        name        = each.value.COUNTRY
        parent_name = each.value.REGION
      }
    }
  }
  depends_on = [dnacenter_area.region]
}

resource "dnacenter_area" "state" {
  for_each = { for u in var.sites : u.SITE_ID => u }
  provider = dnacenter
  parameters {
    type = "area"
    site {
      area {
        name        = each.value.STATE
        parent_name = format("Global/%s/%s", each.value.REGION, each.value.COUNTRY)
      }
    }
  }
  depends_on = [dnacenter_area.country, dnacenter_area.region]
}

resource "dnacenter_area" "city" {
  for_each = { for u in var.sites : u.SITE_ID => u }
  provider = dnacenter
  parameters {
    type = "area"
    site {
      area {
        name        = each.value.CITY
        parent_name = format("Global/%s/%s/%s", each.value.REGION, each.value.COUNTRY, each.value.STATE)
      }
    }
  }
  depends_on = [dnacenter_area.region, dnacenter_area.country, dnacenter_area.state]
}

resource "dnacenter_building" "building" {
  for_each = { for u in var.sites : u.SITE_ID => u }
  provider = dnacenter
  parameters {
    type = "building"
    site {
      building {
        address     = each.value.STREET_ADDRESS
        country     = each.value.COUNTRY
        name        = each.value.SITE
        parent_name = format("Global/%s/%s/%s/%s", each.value.REGION, each.value.COUNTRY, each.value.STATE, each.value.CITY)
      }
    }
  }
  depends_on = [dnacenter_area.region, dnacenter_area.country, dnacenter_area.state, dnacenter_area.city]
}
```

**Comment by mschedrin** [comment]
You might be hitting appliance scaling limit depending on what DNAC size you are using, check out Site elements number in Table 14. 
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/dna-center/nb-06-dna-center-data-sheet-cte-en.html#Appliancescale

**Comment by fmunozmiranda** [comment]
Hi @jschingen could you please send me logs with Debug enabled.
Thank you.

**Comment by jschingen** [comment]
The issue seems to be the format of my data and how your provider updates DNAC. Since some of the data is repeated for each area, region, country, etc., your provider decides to do multiple creates instead of just one. The provider does a GET before creating an area but since the duplicate area is still in progress of being created it sends another create and a race condition ensues. Depending on how fast the first copy of the area can be created before the second copy can create simple errors and have the apply fail or a segmentation fault as shown above.

**Comment by fmunozmiranda** [comment]
@jschingen could you test it with this config:
terraform apply -auto-approve -parallelism=1

**Comment by sdnovation** [comment]
I have the same issue with areas, buildings, and reserved IP pools. Other than that, I have not tried. Sometimes it even crashes on the plan command. With about 100 elements, I had no problem. Once I exceeded this number, problems started. Sometimes it works fine. Other times, I need to repeat the plan or apply 3-8 times until everything is configured in the DNAC. I tried different versions; 1.1.21 seems to be the most sufficient. I don't think it's a DNAC scaling issue, because after several runs, every element is configured.

Running `terraform apply -auto-approve -parallelism=1` did the job, but it significantly increased the time.

**Comment by mschedrin** [comment]
Unfortunaly `-parallelism=1` is the only way to work with DNAC API. The API cannot run more than 1 api job simultaneously, so you have to wait for previous task to complete before sending a new one.

**Comment by zapodeanu** [comment]
@mschedrin This is not completely accurate. There are some APIs with a concurrency of 1, while for the vast majority of the Catalyst Center APIs the concurrency matches the API rate limit.

**Comment by mschedrin** [comment]
That is good news, @zapodeanu. Do you happen to have a link with API limits documentation?

**Comment by fmunozmiranda** [comment]
I think problem here it´s something related to dependency, if there are some sites that need others to be created and aren´t still created at moment of run resource it would fail.
Please see this: https://discuss.hashicorp.com/t/for-each-depends-on-previous-item/14351

**Comment by jschingen** [comment]
@fmunozmiranda Using `parallelism=1` solved the issue while drastically increasing runtime as other people have noted in this thread. Also, if I apply the areas in chunks of 10 there doesn't seem to be an issue. There is a fine balance between size of datasets and parallel API calls.

**Comment by fmunozmiranda** [comment]
Hello, this is not directly a Terraform issue, as what is happening is that creations are not being executed in the required order since Terraform runs in parallel. This is something that could be tried at the TF file level rather than at the provider level. I'll close the issue; let me know if you have any questions.
