### ISSUE TITLE
"dnacenter_pnp_device" Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by HarshadKulkarni** [cisco-en-programmability/terraform-provider-dnacenter#254]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
After apply getting response as a "Error: Provider produced inconsistent result after apply" however devices is getting successfully added to DNAC
**Expected behavior**
There should not be any error in response after executing apply

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

NA

**Environment (please complete the following information):**
* Cisco DNA Center version and patch:  "Version 2.3.5.4-70852-HF3"
* Terraform version: "1.1.31-beta"
[log_1.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/13879005/log_1.txt)

* Cisco DNA Center provider version: Version 2.3.5.4-70852-HF3

* OS Version: 

**Additional context**

**Comment by bvargasre** [comment]
Hi @HarshadKulkarni 

Version 1.1.33-beta has been released. Please test with this new version.
I will close the issue for now. If the problem persists, feel free to reopen the issue.

Best regards
