### ISSUE TITLE
Skip resources meeting a condition in site hierarchy management

### ISSUE THREAD

**Issue by vmautonet** [cisco-en-programmability/terraform-provider-dnacenter#263]
**Is your feature request related to a problem? Please describe.**
I am having my DNAC hierarchy stored in a CSV (format that can be imported through a native feature in DNAC). I can import and manage the hierarchy using this provider just fine. Problem comes when I upload an Ekahau survey into DNAC, which changes the dimensions of the floor. Whenever I want to apply the tf state again, it wants to overwrite the new (and obviously better) dimensions.

**Describe the solution you'd like**
I would like to have an option to skip these floors where the floor length / width are not default (or specific)

**Describe alternatives you've considered**
Importing data source = sitelist and then comparing existing values to those in the CSV; if there is nothing in the csv, use what is in the data source; or maybe not use terraform, use dnacsdk in python and work with json

**Additional context**
The site management is a feature that is most of the time likely managed in a hybrid mode... automated as well as manual.

Thanks for reviewing / considering / teaching me an already existing way I did not find :-)
Vojta

**Comment by vmautonet** [comment]
For now I configured the alternative posted above and skip existing floors, which is not ideal

**Comment by jolstorn** [comment]
This can be solved in your .tf code. Add a lifecycle-block like this:
```
 lifecycle {
    ignore_changes = [
      parameters[0].site[0].floor[0].height,
      parameters[0].site[0].floor[0].length,
      parameters[0].site[0].floor[0].width,
      parameters[0].site[0].floor[0].rf_model
    ]
  }
```

**Comment by bvargasre** [comment]
Hi @vmautonet

We have reviewed your suggestion to add this feature on the provider's side. However, implementing this change could potentially disrupt Terraform's functionality.

As mentioned by jolstorn, the best approach in this case is to use the ignore_changes argument. This will allow you to achieve the desired behavior without risking any disruptions to Terraform's operations.

If you have any further questions or concerns, please don't hesitate to reopen this issue or create a new one.

Best regards.
