### ISSUE TITLE
IP Pool - Virtual Network

### ISSUE THREAD

**Issue by jbogarin** [cisco-en-programmability/terraform-provider-dnacenter#4]
A couple of issues in the resource for this API. First, there are mandatory fields as part of TF resource implementation which shouldn’t be mandatory (API allows for them to be optional). For example, below is a usage of this resource:

 

```
resource "dna_sda_fabric_ip_pool_in_vn" "ip_pool_guest" {
  provider   = dnacenter
  virtual_network_name = "Test_VN"
  ip_pool_name = "Test_Pool2" 
  traffic_type = "Data"
  authentication_policy_name = "Test_policy"
  scalable_group_name = ""
  is_l2_flooding_enabled = false
  is_this_critical_pool = false
  pool_type = "Generic"
}
```

Variables `pool_type`, `is_this_critical_pool`, `is_l2_flooding_enabled` are all optional fields but the resource forces you to use it.

Secondly, this resource does not seem to work. Using the same exact values, the API executes without any issues however the TF resource produces no result and does not work.

 
```
[
    {
        "virtualNetworkName": "Test_VN",
        "ipPoolName": "Test_Pool2",
        "trafficType": "Data",
        "authenticationPolicyName": "test",
        "scalableGroupName": "",
        "isL2FloodingEnabled": false,
        "isThisCriticalPool": false,
        "poolType": "Generic"
    }
]
```

**Comment by wastorga** [comment]
The latest version, 0.0.4, addressed this issue.

**Comment by wastorga** [comment]
Feel free to reopen if the problem still exists. Thank you.
