### ISSUE TITLE
double name in ID [id=name:=name:=XXX] for parent_name

### ISSUE THREAD

**Issue by pamosima** [cisco-en-programmability/terraform-provider-dnacenter#43]
Hi there,

I see an issue when using dnacenter_site.XXX.id for parent_name: 

### Terraform Version
Terraform v0.14.9
+ provider registry.terraform.io/cisco-en-programmability/dnacenter v0.3.0-beta

### Affected Resource(s)
Please list the resources as a list, for example:
- dnacenter_site

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
terraform {
  required_providers {
    dnacenter = {
      source = "cisco-en-programmability/dnacenter"
      version = "0.3.0-beta"
    }
  }
}
##################################################################################
# VARIABLES
##################################################################################

variable "dnac_username" {}
variable "dnac_password" {}
variable "dnac_url" {}

##################################################################################
# PROVIDERS
##################################################################################

provider "dnacenter" {
  # Configuration options
  # More info at https://registry.terraform.io/providers/cisco-en-programmability/dnacenter/latest/docs#example-usage

    # Cisco DNA Center user name
    username = var.dnac_username

    # Cisco DNA Center password
    password = var.dnac_password

    # Cisco DNA Center base URL, FQDN or IP
    base_url = var.dnac_url

    # Boolean to enable debugging
    debug = "true"
    # it can be set using the environment variable DNAC_DEBUG

    # Boolean to enable or disable SSL certificate verification
    ssl_verify = "false"
    # it can be set using the environment variable DNAC_SSL_VERIFY
}

resource "dnacenter_site" "customer-c" {
  provider = dnacenter
  parameters {
    site {
      area {
        name = "Customer C"
        parent_name = "Global"
      }
    }
  type = "area"
  }
}
resource "dnacenter_site" "customer-c_zurich" {
  depends_on = [ dnacenter_site.customer-c ]
  provider = dnacenter
  parameters {
    site {
      area {
        name = "Zurich"
        parent_name = dnacenter_site.customer-c.id
      }
    }
  type = "area"
  }
}

### Debug Output
dnacenter_site.customer-c: Creating...
dnacenter_site.customer-c: Creation complete after 8s [id=name:=Global/Customer C]
dnacenter_site.customer-c_zurich: Creating...
dnacenter_site.customer-c_zurich: Creation complete after 6s [id=name:=name:=Global/Customer C/Zurich]

### Expected Behavior
id should be [id=name:=Global/Customer C/Zurich]

### Actual Behavior
double name in it [id=name:=name:=Global/Customer C/Zurich]

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by fmunozmiranda** [comment]
Hi @pamosima, we are working on it, we wil have you updated.

**Comment by fmunozmiranda** [comment]
Hey @pamosima , I see that you are trying to access ```parent_name``` through the generated id for terraform, that can be problematic, I recommend you to access the properties in ```item```, I think it will work for you `` `site_name_hierarchy```, I'll give you a test that worked for me. Try it and let us know if it works for you.

```tf
resource "dnacenter_site" "customer-c" {
  provider = dnacenter
  parameters {
  site {
      area {
        name = "Customer C"
        parent_name = "Global"
      }
    }
    type = "area"
  }
}
resource "dnacenter_site" "customer-c_zurich" {
  depends_on = [ dnacenter_site.customer-c ]
  provider = dnacenter
  parameters {
    site {
      area {
        name = "Zurich"
        parent_name = dnacenter_site.customer-c.item.0.site_name_hierarchy
      }
    }
    type = "area"
  }
}
```

**Comment by pamosima** [comment]
Hi @fmunozmiranda, that works great. Thanks a lot. Could you add that to the example?
