### ISSUE TITLE
DNAC SDA Fabric Site - Failed

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#61]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?

**Describe the bug**
dnacenter_sda_fabric_site (Resource) - fails.

**Expected behavior**
DNAC site should be added as SDA Fabric Site.

I’ve been following the documentation on github.com and registry.terraform.io of how to create SDA fabric,

DNAC version is 2.2.3.5

I’ve tired with both provider version 0.3.0 and 1.0.0-beta 

In version 0.3.0 there are:
dnacenter_sda_fabric (Resource)
dnacenter_sda_fabric_site (Resource)

With version 0.3.0 - If I include the dnacenter_sda_fabric (Resource) – it crashes the plugin. 

 
![Screenshot 2022-07-08 at 15 59 54](https://user-images.githubusercontent.com/106110026/178013652-a679b566-b8a5-43be-92dd-0adaea86941d.png)

With version 1.0.0-beta – it tells me that this is not supported:

  
![Screenshot 2022-07-08 at 16 01 22](https://user-images.githubusercontent.com/106110026/178013747-86478a60-dd14-4fb4-b37a-46e6464a896b.png)

Although it’s on githum.com listed in examples for 1.0.0-beta
https://github.com/cisco-en-programmability/terraform-provider-dnacenter/blob/main/examples/samples/resources/dnacenter_sda_fabric/main.tf

So now I’m only trying with: dnacenter_sda_fabric_site (Resource)
With both versions I get the same problem about siteNameHierarchy:

 
![Screenshot 2022-07-08 at 16 57 38](https://user-images.githubusercontent.com/106110026/178018023-b38d6776-c67a-426d-bbe6-cd44bc80e404.png)

But if I create the SDA Fabric Site manually on DNAC and then run “terraform apply” –  it run’s without any errors and I can also use "terraform destroy" to delete the SDA Fabric Site:

 
![Screenshot 2022-07-08 at 16 59 20](https://user-images.githubusercontent.com/106110026/178018455-def188f1-22b7-47b6-a77f-ba2051c39660.png)

![Screenshot 2022-07-08 at 17 00 46](https://user-images.githubusercontent.com/106110026/178018605-809e82f9-22a6-4171-9d3b-7f1d9484fe8a.png)

**Running the API directly from DNAC works fine:**

 
![Screenshot 2022-07-08 at 16 25 10](https://user-images.githubusercontent.com/106110026/178014905-7276da43-1855-492e-86a4-a08f10911182.png)

**Comment by fmunozmiranda** [comment]
Hi @artur-tekieli , thanks for report and give a detailed resume of problem, team is going to work on it and will keep you informed.

**Comment by fmunozmiranda** [comment]
Hey @artur-tekieli , once again thanks for reporting the problems found, a new version (1.0.1-beta) was published in which your problem should be solved, try it and let us know if it worked for you.

**Comment by artur-tekieli** [comment]
Hi @fmunozmiranda, I've tested it and it works - thanks !

I faced another issue with: dnacenter_site (Resource) - it works fine in v0.3.0
but not in v1.0.0/1.0.1-beta - it complains about 
"Invalid address to set: []string{"item", "0", "additional_info", "0", "name_space"}"

Is version 1.0.x suppose to be fully backward compatible with DNAC 2.2.3.5 ? I don't have version 2.3.3.0 to test it with.
But if yes I can open a new issue for this.

**Comment by fmunozmiranda** [comment]
@artur-tekieli, It would be great if you opened a new issue to see it in detail together with the team, it would be very helpful if you detailed the test you did, it would also be great to have a screenshot of a successful API call. If everything worked fine for you, please close this issue and open the other one, thank you very much for reporting the detected bugs, you help us improve.
