### ISSUE TITLE
Add border device in SDA Fabric

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#68]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
 (dnacenter_sda_fabric_border_device) Resource fails to Add border device in SDA Fabric 

**Expected behavior**
API call should succeed and device should be configured as Border, Control Plane and Edge. If all three roles are included.

**Screenshots**
when '[' and ']' are used with "virtualNetwork":  the API fails:
![Screenshot 2022-07-11 at 19 38 10](https://user-images.githubusercontent.com/106110026/178326932-6971a567-6b15-4fe5-8088-001ae0b83537.png)

terraform also includes '[' and ']' - so it fails.

![Screenshot 2022-07-11 at 19 44 13](https://user-images.githubusercontent.com/106110026/178327692-a1f7057e-ef9c-42f9-80e8-8bdcb9776390.png)

However without '[' and ']'  it works:

![Screenshot 2022-07-11 at 19 42 08](https://user-images.githubusercontent.com/106110026/178326090-c03b36f7-8137-4a7a-9e69-a7f3e5b06e1f.png)

**Environment (please complete the following information):**
* DNAC = 2.2.3.5
* Terraform version: 1.2.1
* Cisco DNA Center provider version: 1.0.2-beta
* OS Version: 

**Additional context**
It seems that's how this API is also documented on DNAC:

![Screenshot 2022-07-11 at 19 35 50](https://user-images.githubusercontent.com/106110026/178327590-51fda33b-ac2f-4e5d-9504-876190e154b1.png)

**Comment by fmunozmiranda** [comment]
@artur-tekieli version 1.0.2-beta was published with a possible solution to your problem, please verify it's now working for you and let us know how it went.

**Comment by artur-tekieli** [comment]
@fmunozmiranda, I still see an error although its different:

![Screenshot 2022-07-11 at 21 55 30](https://user-images.githubusercontent.com/106110026/178350966-9aa2120d-1f2f-4022-98da-b0e440ee248b.png)

The device is provisioned and assigned to site:

![Screenshot 2022-07-11 at 22 17 48](https://user-images.githubusercontent.com/106110026/178351024-9808304c-8a14-4a17-ad34-d8471b903d9a.png)

**Comment by fmunozmiranda** [comment]
@artur-tekieli could you please try it again with version 1.0.4-beta?, I need your confirmation because on my part I need data to prove it, thank you.

**Comment by fmunozmiranda** [comment]
@artur-tekieli could you export this env variable or include debug in provider configuration and show me all answer you have please?
## Env Variable:
```shell
TF_LOG=DEBUG
```

## Provider configuration:
```tf
provider "dnacenter" {
  debug = "true"
}

**Comment by fmunozmiranda** [comment]
@artur-tekieli sorry for the delay, we had some problems when publishing, there is a new version in which your problem should be solved, check that the version you are using is 1.0.5-beta, also look at the example: `https ://github.com/cisco-en-programmability/terraform-provider-dnacenter/blob/main/examples/resources/dnacenter_sda_fabric_border_device/resource.tf`, if the change does not work for you it would be very important for us that you pass us your file test(tf file) along with the full response with DEBUG enabled.

Note:
Thanks for reporting, it helps us a lot.

**Comment by artur-tekieli** [comment]
@fmunozmiranda - I can confirm in my test that it works. Thanks.
