### ISSUE TITLE
Update terraform provider version to match go sdk version of DNAC

### ISSUE THREAD

**Issue by robertcsapo** [cisco-en-programmability/terraform-provider-dnacenter#7]
this terraform provider is lagging behind the sdk version
https://github.com/cisco-en-programmability/dnacenter-go-sdk

as a result, issues with current ip pool isn't fixed.
https://github.com/hashicorp/terraform/issues/28728

while it's fixed in the golang sdk
https://github.com/cisco-en-programmability/dnacenter-go-sdk/issues/5

suggestion:
publish a new updated version of https://registry.terraform.io/providers/cisco-en-programmability/dnacenter/latest

**Comment by jbogarin** [comment]
Robert,

We are working on making some changes to the SDK that will be disruptive, mainly migrating from things like PutCredentials to UpdateCredentials. Once that's done, we will update the Terraform Provider.

**Comment by wastorga** [comment]
The latest version, 0.0.4, addressed this issue.
It is using the tagged version of the SDK v0.1.0.
