### ISSUE TITLE
Reserve IP subpool for a site

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#70]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
Its not really a bug but more of a question maybe an enhancement.
When reserving an IP pools I need to reference  site_id, 
but site_id are only after a DNAC site is configured.  So it makes the automation a bit more difficult to achieve: 

![Screenshot 2022-07-11 at 22 30 11](https://user-images.githubusercontent.com/106110026/178352726-1bb3ac5a-309f-403d-a15e-2f545112832c.png)

```
resource "dnacenter_reserve_ip_subpool" "example" {
   provider = dnacenter
   depends_on = [ dnacenter_global_pool.example ]
 
   parameters {
    ...
     name               = "Cape_Town_Corp_VN"
     site_id            = "5812a67c-4939-44f9-92cc-81ceac6019cc" **<<<<<<<<<<<<<<<<<<**
     type               = "Generic"
  }
}

```
Is it not possible to reference "site_name_hierarchy" = "Global/SouthAfrica/CapeTown" - instead of site_id ?

This would make it much more easier to use.

**Comment by fmunozmiranda** [comment]
I think you can solve it without an enhancement doing something like this:
```tf
resource "dnacenter_site" "example" {
  provider = dnacenter
  parameters {
    site {
      building {
        name        = "testBuilding"
        address     = "255 China Basin Street, San Francisco, California 94158, United States"
        parent_name = "Global"
        latitude    = 37.77178651716143
        longitude   = -122.39062051589885
      }
    }
    type = "building"
  }
}
resource "dnacenter_reserve_ip_subpool" "example" {
   provider = dnacenter
   depends_on = [ dnacenter_global_pool.example ]
 
   parameters {
    ...
     name               = "Cape_Town_Corp_VN"
     site_id            =  dnacenter_site.example.0.id
     type               = "Generic"
  }
}
```
Try it and let us know if works and it's what you want.

**Comment by artur-tekieli** [comment]
@fmunozmiranda  I've tried it:

```
resource "dnacenter_site" "building" {
  provider = dnacenter
  depends_on = [ dnacenter_site.area ]
  parameters {
    site {
      building {
        name = var.building
        address     = "63 Victoria Rd, Camps Bay, Cape Town, 8040, South Africa"
        latitude    = -33.9508898420
        longitude   = 18.377273855178373
        parent_name = "Global/SouthAfrica"
      }
    }
    type = "building"
  }
}
```


```
resource "dnacenter_reserve_ip_subpool" "building" {
  provider = dnacenter
  depends_on = [ dnacenter_global_pool.example ]

  parameters {
    ...
    name               = "Cape_Town_Corp_VN"
    site_id            = dnacenter_site.building.item.0.id
    type               = "Generic"
  }
}
```

And get this error:

<img width="643" alt="Screenshot 2022-07-12 at 07 04 07" src="https://user-images.githubusercontent.com/106110026/178412772-fe964590-c687-4044-bfb0-6e8175d2c7ec.png">

**Comment by artur-tekieli** [comment]
@fmunozmiranda  - Yes that's exactly what I wanted - Thanks!

**Comment by artur-tekieli** [comment]
@fmunozmiranda   - Yes that's exactly what I wanted - Thanks!
