### ISSUE TITLE
dnacenter_discovery - terraform destroy deletes all discoveries

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#76]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
With ```resource "dnacenter_discovery" ``` -  ```terraform apply``` will create a new discovery in DNAC. All works fine.
But with ```terraform destroy``` - all previous discoveries are deleted from DNAC and not just the one created. 

**Expected behavior**
Only the discovery created with ```terraform apply``` should be deleted.

**Screenshots**
Here are the debugs for both apply and destroy:
[apply_tf_debug.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9127889/apply_tf_debug.txt)

[destroy_tf_debug.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9127890/destroy_tf_debug.txt)

**Environment (please complete the following information):**
* DNAC = 2.2.3.5
* Terraform version: 1.2.1
* Cisco DNA Center provider version:1.0.6-beta

**Additional context**

**Comment by fmunozmiranda** [comment]
Hey @artur-tekieli  we're working on it.

**Comment by fmunozmiranda** [comment]
@artur-tekieli there is a new version (1.0.7-beta) try it with that version and let us know how goes.

**Comment by artur-tekieli** [comment]
@fmunozmiranda, Yes it works.
