### ISSUE TITLE
Display nested schema from dnacenter_sda_fabric_border_device (Data Source)

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#77]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
I have a question on how do I display nested schema for SDA border as documented here:
https://registry.terraform.io/providers/cisco-en-programmability/dnacenter/latest/docs/data-sources/sda_fabric_border_device#nestedobjatt--item--payload--device_settings--ext_connectivity_settings

The info I want to display is:
Nested Schema for item.payload.device_settings.storage.l3_handoff:
* local_ip_address 
* remote_ip_address 
* virtual_network 
* vlan_id 

**Screenshots**
![Screenshot 2022-07-17 at 16 52 11](https://user-images.githubusercontent.com/106110026/179404004-4a4c4922-5f56-4687-884e-3735002808da.png)

**Environment (please complete the following information):**
* DNAC = 2.2.3.5
* Terraform version: 1.2.1
* Cisco DNA Center provider version: 1.0.6-beta

**Comment by fmunozmiranda** [comment]
@artur-tekieli, I think documentation is wrong, could you pass your tfstate file for help you?

**Comment by artur-tekieli** [comment]
@fmunozmiranda Here is the requested info:
[tf_debug_border_info.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9135497/tf_debug_border_info.txt)

[border-api.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9135498/border-api.txt)

**Comment by artur-tekieli** [comment]
@fmunozmiranda, that works. Thanks.
