### ISSUE TITLE
Destroying many areas, buildings, floors fails

### ISSUE THREAD

**Issue by wiwa1978** [cisco-en-programmability/terraform-provider-dnacenter#87]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**
Creating 1x area, 3x buildings and 15x floors per building at once Creation works perfectly for all these 49 objects, they appear in DNAC. Note: these numbers were chosen to avoid the rate limiting of 100 objects per minute.

When using `terraform destroy` to delete these objects, Terraform tells it destroyed all objects (the remaining state file is empty as well after this process) but on DNAC the objects are not deleted. Some objects are but others are still visible (see screenshot)

```
~/dnacenter > terraform destroy -auto-approve
....
dnacenter_site.floor["floor5_building_nw03"]: Destroying... [id=name:=Global/Norway/NW03/Floor5]
dnacenter_site.floor["floor8_building_nw03"]: Destroying... [id=name:=Global/Norway/NW03/Floor8]
dnacenter_site.floor["floor2_building_nw02"]: Destroying... [id=name:=Global/Norway/NW02/Floor2]
dnacenter_site.floor["floor5_building_nw03"]: Destruction complete after 0s
dnacenter_site.floor["floor8_building_nw03"]: Destruction complete after 0s
dnacenter_site.floor["floor2_building_nw02"]: Destruction complete after 0s
dnacenter_site.floor["floor14_building_nw01"]: Destruction complete after 1s
dnacenter_site.floor["floor10_building_nw02"]: Destruction complete after 1s
dnacenter_site.floor["floor9_building_nw03"]: Destruction complete after 1s
dnacenter_site.floor["floor9_building_nw01"]: Destruction complete after 1s
dnacenter_site.floor["floor12_building_nw03"]: Destruction complete after 1s
dnacenter_site.floor["floor9_building_nw02"]: Destruction complete after 1s
dnacenter_site.floor["floor12_building_nw02"]: Destruction complete after 1s
dnacenter_site.building["building_nw01"]: Destroying... [id=name:=Global/Norway/NW01]
dnacenter_site.building["building_nw02"]: Destroying... [id=name:=Global/Norway/NW02]
dnacenter_site.building["building_nw03"]: Destroying... [id=name:=Global/Norway/NW03]
dnacenter_site.building["building_nw02"]: Destruction complete after 0s
dnacenter_site.building["building_nw01"]: Destruction complete after 0s
dnacenter_site.building["building_nw03"]: Destruction complete after 0s
dnacenter_site.area["area_norway"]: Destroying... [id=name:=Global/Norway]
dnacenter_site.area["area_norway"]: Destruction complete after 1s

Destroy complete! Resources: 49 destroyed.

```
**Expected behavior**
Terraform would correctly destroy all objects it created and not leave objects on DNAC.

**Screenshots**
The below screenshot shows the objects after doing 'terraform destroy'. Expected would be that no area 'Norway', associated buildings and floors would be visible any more.

![Screenshot 2022-09-21 at 14 01 16](https://user-images.githubusercontent.com/4012455/191499578-412eff92-bf73-4eee-9f32-367245a15b30.png)

**Environment (please complete the following information):**
* DNAC = 2.2.3.5
* Terraform version: 1.9.1
* Cisco DNA Center provider version: 1.0.7-beta

**Additional context**
The terraform logs for creating the objects and destroying the objects are attached. 
  * [terraform_create.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9616344/terraform_create.log) 
   * [terraform_destroy.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9616345/terraform_destroy.log)

Terraform files to reproduce this (only change the DNAC instance in provider.tf)
  * [Terraform_Sites_Github.zip](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9616394/Terraform_Sites_Github.zip)

**Comment by fmunozmiranda** [comment]
Hi @wiwa1978, could you please verify on ISE API, one of `executionId` params given on `terraform_destroy.log` and show us API response please?

**Comment by wiwa1978** [comment]
I reproduced the issue again. I created 1x area, 3x buildings and 15x floors per building at once. All objects were created successfully. Then I waited for 5 minutes and I did a `terraform destroy`. 

The output was again `Destroy complete! Resources: 49 destroyed.` but in reality there were still floors remaining. Here is a view of DNAC after `terraform destroy`

![image](https://user-images.githubusercontent.com/4012455/191738601-9474a1f4-3c5e-4280-9303-802a02d00bf2.png)

I checked the following for floor 1 (was correctly destroyed and hence not visible at DNAC)

```
https://{{dnac}}/dna/intent/api/v1/site?name=Global/Norway/NW01/Floor1

{
    "message": [
        "The input site is not valid or site is not present."
    ],
    "response": []
}
```
and for Floor 3 (was still visible on DNAC, so looks like this was not correctly destroyed)
```
https://{{dnac}}/dna/intent/api/v1/site?name=Global/Norway/NW01/Floor3

{
    "response": [
        {
            "parentId": "513cb7d3-1599-4950-9af6-d50934adab0e",
            "additionalInfo": [
                {
                    "nameSpace": "mapGeometry",
                    "attributes": {
                        "offsetX": "0.0",
                        "offsetY": "0.0",
                        "length": "300.0",
                        "width": "300.0",
                        "height": "50.0"
                    }
                },
                {
                    "nameSpace": "mapsSummary",
                    "attributes": {
                        "rfModel": "50050",
                        "imageURL": "",
                        "isCadFile": "false",
                        "floorIndex": "1"
                    }
                },
                {
                    "nameSpace": "Location",
                    "attributes": {
                        "address": "34 Grønland, Drammen, Viken 3045, Norway",
                        "addressInheritedFrom": "513cb7d3-1599-4950-9af6-d50934adab0e",
                        "type": "floor"
                    }
                }
            ],
            "name": "Floor3",
            "instanceTenantId": "5f0c4ccffd099c00ca183c17",
            "id": "8c354e18-7bfc-4699-92b3-261a4fbcabc5",
            "siteHierarchy": "1eb07797-0624-4bdf-ab10-941f56bf75a2/4be8b7d0-c076-4e4d-9586-99bf65081d72/513cb7d3-1599-4950-9af6-d50934adab0e/8c354e18-7bfc-4699-92b3-261a4fbcabc5",
            "siteNameHierarchy": "Global/Norway/NW01/Floor3"
        }
    ]
}
```

In the terraform log for Floor 3 I could see the following 429 message:

```
~~~ REQUEST ~~~
GET  /dna/intent/api/v1/site?name=Global%2FNorway%2FNW02%2FFloor3  HTTP/1.1
HOST   : 10.50.222.124
HEADERS:
	Accept: application/json
	Content-Type: application/json
	User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
	X-Auth-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmM1M2I4YmYzZWQ4NjEyNzkwYmMyOTIiLCJhdXRoU291cmNlIjoiaW50ZXJuYWwiLCJ0ZW5hbnROYW1lIjoiVE5UMCIsInJvbGVzIjpbIjVmMGM0Y2QwZmQwOTljMDBjYTE4M2MxOSJdLCJ0ZW5hbnRJZCI6IjVmMGM0Y2NmZmQwOTljMDBjYTE4M2MxNyIsImV4cCI6MTY2Mzg1MDc3OCwiaWF0IjoxNjYzODQ3MTc4LCJqdGkiOiIxZjNjNThiNi1kNDEzLTRmOTQtYjE5MS01YzEwMzg0ZWM1YzkiLCJ1c2VybmFtZSI6IndpbSJ9.HksKXIWJvKWxowhGf4yCzd5hUya6QailK-2PEam9cxAO38KfaklFbJDIpI0uqav8BB2TLjtseFJG-yzgYgKIvFJfAfnDWwQ4CuwCRBlG8Wp2Z6lFTMJMCgz902HVyLnZhuFfmFg4tFoId-mzrAL3aiF8g6j6W8rCLoVNXFgJOgd2RexEx2jBQaid9p-q2H5MnPIYXqxUCDOIH2KrwMDxuO5iVpuxT33dccqGtsInZi-g5ocfnyF4dJ5eaAdfbRe6pAVoHjKv5YqxqFv4JjCmLtawK87hCdjUnLNmsB9587ByM82GIe_kixnxRdphuU17tUd8fMQH-FLnSfmpwabd6A
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 429 Too Many Requests
PROTO        : HTTP/1.1
RECEIVED AT  : 2022-09-22T13:46:21.153986+02:00
TIME DURATION: 95.31225ms
HEADERS      :
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 451
	Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:
	Content-Type: application/json
	Date: Thu, 22 Sep 2022 11:46:21 GMT
	Pragma: no-cache
	Server: webserver
	Strict-Transport-Security: max-age=31536000; includeSubDomains
	Via: api-gateway
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Request-Id: c3af5c3ec6995d3e0d4a958d7d595cda
	X-Xss-Protection: 1
BODY         :
{
   "error": "Rate Limit exceeded; BapiName: Get Site, RateLimit config details: RateLimitContext{rate=100, windowUnit='minute', windowDuration=1, maxConcurrentExecutionsPermitted=0}",
   "bapiExtendedStatusCode": "REJECTED_ABOVE_THROTTLE_LIMIT",
   "bapiExtendedStatusDescription": "For BAPI: Get Site, maximum allowed BAPI instances per 1 minute is 100. The limit has been reached for the time-window between Thu Sep 22 11:45:21 UTC 2022 and now"
}
```

The rate limit is `For BAPI: Get Site, maximum allowed BAPI instances per 1 minute is 100. ` I'm creating 49 objects, waited 5 minutes and destroyed these 49 objects. So not sure I understand how the rate limit can kick in.

Some observations:
- I don't seem to find a executionId for the objects that were still visible on DNAC.
- waiting did not help, the objects were also not eventually deleted. So I have the impression the API does not take additional time
- In any case, terraform should not display that 49 resources were destroyed if the rate limit prevented from destroying them correctly.

**Comment by wiwa1978** [comment]
Some additional tests:

- created 1 area, 3 buildings and 10 floors per building: total 34 objects. All floors and buildings got deleted, except not the area itself. For that I saw a single `429 Too many requests` in the log file

- created 1 area, 3 buildings and 10 floors for building 1 and 2 and 9 floors for building 3: total 33 objects. All floors, buildings and area got deleted. No `429 Too many requests` in the log file

**Comment by fmunozmiranda** [comment]
Hi @wiwa1978 there's a new provider version (1.0.8-beta), please try it again and let us know if now works well for you.

**Comment by wiwa1978** [comment]
Not fixed using 1.0.8-beta. If you want to reproduce, use the Terraform_Sites_Github.zip file.

**Comment by fmunozmiranda** [comment]
@wiwa1978  Try it again with 1.0.9-beta, and feel free to close it if works for you or comment if it is required.

**Comment by fmunozmiranda** [comment]
Hey @wiwa1978 please update us in next 24 hours or issue will be closed due inactivity.

**Comment by fmunozmiranda** [comment]
Closed due inactivity.
