### ISSUE TITLE
Renaming floors not working correct

### ISSUE THREAD

**Issue by wiwa1978** [cisco-en-programmability/terraform-provider-dnacenter#88]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**

I'm performing following use case:

- Step 1: Create 1 area, 1 building and 2 floors (e.g floors have name Floor 1 and Floor2)
- Step 2: Rename 1 floor name (other floor name untouched) to new name (e.g. Floor1-step2)
- Step 3: Rename same floor name again (e.g from Floor1-step2 to Floor1-step3)

This use case expects same amount of floors in the end, just with a new name. Instead, DNAC shows 3 floors after this use case is executed.

- After step 1: two floors are created with name Floor 1 and Floor 2
- After step 2: two floors with name Floor1-step2 and Floor 2 
- After step 3: three floors with names Floor1-step2, Floor1-step3, Floor2

Step 1 and step 2 are expected behaviour. Step 3 is not executed correctly (see below to the output of the `terraform plan` and `terraform apply`. It should rename the floor and not create a new floor and leaving the previous floor on DNAC.

After step 1:
 - `terraform plan`: 4 to add, 0 to change, 0 to destroy
 - `terraform apply`: 4 added, 0 changed, 0 destroyed

After step 2:
- `terraform plan`: 0 to add, 1 to change, 0 to destroy
- `terraform apply`: 0 added, 1 changed, 0 destroyed

After step 3:
- `terraform plan`: 1 to add, 0 to change, 0 to destroy
- `terraform apply`: 1 added, 0 changed, 0 destroyed

Important note: in step 3 -when doing Terraform apply- the output shows the following message "Objects have changed outside of Terraform". Look at file `Usecase_Execution.pdf`. I can guarantee that no changes were made on DNAC during this test.

**Expected behavior**

- After step 1: two floors are created with name Floor 1 and Floor 2
- After step 2: two floors exist on DNAC with name Floor1-step2 and Floor 2 
- After step 3: two floors exist on DNAC with names Floor1-step3, Floor2

**Screenshots**

After step 1 (create 2 floors with name Floor1 and Floor2)
![image](https://user-images.githubusercontent.com/4012455/191714212-404f3839-62e8-4fa7-b85e-76d521da229a.png)

After step 2: rename Floor1 from Floor1 to Floor1-step2
![image](https://user-images.githubusercontent.com/4012455/191714253-7c81ec61-5461-4a4f-953c-57f4f4b2c493.png)

After step 3: rename Floor1-step2 to Floor1-step3
![image](https://user-images.githubusercontent.com/4012455/191714314-50b47c96-1c42-4963-9df4-349f83e1b3a9.png)

**Environment (please complete the following information):**
- DNAC = 2.2.3.5
- Terraform version: 1.9.1
- Cisco DNA Center provider version: 1.0.7-beta

**Additional context**

- This has been tested for floors. Maybe same behaviour for areas and buildings.

Attached are:
- PDF file `Usecase_Ececution.pdf: capture of the CLI output from terraform commands per step. 
- Terraform logs per step

[Usecase_Execution.pdf](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624523/Usecase_Execution.pdf)
[terraform_step1.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624534/terraform_step1.log)
[terraform_step2.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624535/terraform_step2.log)
[terraform_step3.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624536/terraform_step3.log)

**Comment by fmunozmiranda** [comment]
Hi @wiwa1978 there's a new provider version (1.0.8-beta), please try it again and let us know if now works well for you.

**Comment by wiwa1978** [comment]
Fixed with 1.0.8-beta
