### ISSUE TITLE
Destroying renamed object does not remove it from DNAC

### ISSUE THREAD

**Issue by wiwa1978** [cisco-en-programmability/terraform-provider-dnacenter#89]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?

**Describe the bug**

I'm performing following use case:

- Step 1: Create 1 area, 1 building and 2 floors (e.g  Floor 1 and Floor3)
- Step 2: Rename Floor1 to Floor1-updated
- Step 3: Destroy all objects

This use case expects that in the end all objects are destroyed. Instead -after running `terraform destroy`- the renamed floor remains visible on DNAC.

After step 1:
 - `terraform plan`: 4 to add, 0 to change, 0 to destroy
 - `terraform apply`: 4 added, 0 changed, 0 destroyed

After step 2:
- `terraform plan`: 0 to add, 1 to change, 0 to destroy
- `terraform apply`: 0 added, 1 changed, 0 destroyed

After step 3:
- `terraform plan`: 0 to add, 0 to change, 3 to destroy
- `terraform destroy`: 0 added, 0 changed, 3 destroyed

**Expected behavior**

- After step 1: two floors are created with name Floor 1 and Floor 3
- After step 2: two floors exist on DNAC with name Floor1-updated and Floor 3
- After step 3: all objects (4 in total: 1 area, 1 building and 2 floors) are destroyed and not visible on DNAC. Instead, the updated floor remains visible at DNAC

**Screenshots**

After step 1 (create 2 floors with name Floor1 and Floor3)
![image](https://user-images.githubusercontent.com/4012455/191724284-8073d4f1-7d4f-4825-bd45-de08572d814a.png)

After step 2: rename Floor1 from Floor1 to Floor1-updated
![image](https://user-images.githubusercontent.com/4012455/191724302-5055a9a4-b61c-426f-bbd0-5af008655130.png)

After step 3: destroy all objects
![image](https://user-images.githubusercontent.com/4012455/191724344-b165678e-12ac-46e8-89b8-f2012df018a9.png)

**Environment (please complete the following information):**
- DNAC = 2.2.3.5
- Terraform version: 1.9.1
- Cisco DNA Center provider version: 1.0.7-beta

**Additional context**

- I have the feeling this might be related to same issue as #88 
- This has been tested for floors. Maybe same behaviour for areas and buildings.

Attached are:
- PDF file `Usecase_Ececution.pdf: capture of the CLI output from terraform commands per step. 
- Terraform logs

[terraform.log](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624792/terraform.log)
[Use Case.pdf](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/9624802/Use.Case.pdf)

**Comment by fmunozmiranda** [comment]
Hi @wiwa1978 there's a new provider version (1.0.8-beta), please try it again and let us know if now works well for you.

**Comment by wiwa1978** [comment]
Fixed with 1.0.8-beta
