### ISSUE TITLE
Terraform import using site_id

### ISSUE THREAD

**Issue by pholos** [cisco-en-programmability/terraform-provider-dnacenter#98]
When I try to import a site from dna center into terraform using the site id. Terraform imports all sites/buildings and floors into my resources. The operation works using the API  .
The terraform version I'm using is 1.2.3

The API call result looks like this ; 
`{'response': {'parentId': '225aaafb-b480-49e9-9bbc-005a5c04a8e9', 'additionalInfo': [{'nameSpace': 'Location', 'attributes': {'addressInheritedFrom': '3e01e07e-b896-455e-8551-d45df306f68c', 'type': 'area'}}], 'name': 'test', 'instanceTenantId': '6053363689361a00c4bfb226', 'id': '3e01e07e-b896-455e-8551-d45df306f68c', 'siteHierarchy': '225aaafb-b480-49e9-9bbc-005a5c04a8e9/3e01e07e-b896-455e-8551-d45df306f68c', 'siteNameHierarchy': 'Global/test'}}`

The command I used to import my resource into terraform is
` terraform import dnacenter_site.site 3e01e07e-b896-455e-8551-d45df306f68c`

**Comment by fmunozmiranda** [comment]
@pholos, could you try the import with this format:
terraform import dnacenter_site.site "site_id:=<id>"
I should update documentation, changing the import example.

If it works for you, let us know it.

**Comment by pholos** [comment]
@fmunozmiranda I tried using the format you suggested. This is the result : 
`{
  "version": 4,
  "terraform_version": "1.3.2",
  "serial": 11,
  "lineage": "8faffac9-a1a4-c44d-68ec-840ce269d44d",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "dnacenter_site",
      "name": "import",
      "provider": "provider[\"registry.terraform.io/cisco-en-programmability/dnacenter\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "site_id:=3e01e07e-b896-455e-8551-d45df306f68c",
            "item": [
              {
                "additional_info": [],
                "id": "",
                "instance_tenant_id": "",
                "name": "",
                "parent_id": "",
                "site_hierarchy": "",
                "site_name_hierarchy": ""
              }
            ],
            "last_updated": null,
            "parameters": []
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
  ],
  "check_results": null
}
`
No data is retrieved in this case

**Comment by fmunozmiranda** [comment]
Could you please pass me your import line?
I test it like this:
`terraform import dnacenter_site.example "site_id:=712fe769-78c9-4766-9189-165caa042eea"`
And it works for me.

**Comment by pholos** [comment]
I actually tried it again and it works 
Thank you !
